### ISSUE TITLE
ML papers top 10 summarisation not released for the weeks 20-27th .

### ISSUE THREAD

**Issue by dhruvmalik007** [dair-ai/ML-Papers-of-the-Week#15]
## Context:

I am regular follower of this repository (both on the GitHub and on X) and really appreciate people working to maintain this repo to get latest applied ML papers. it  seems that for the week 20th - 26th November there was only post thread published on X but not here . maybe the suggestion is to have an CI/CD that published the thread and the GitHub PR to update the summary of the papers at same time .

**Comment by simonprovost** [comment]
+1 !
